server:
  port: 10002
spring:
  application:
    name: iCoupon-distribution
  datasource:
    url: jdbc:mysql://192.168.17.128:3306/coupon?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 192.168.17.128
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.17.128:8848
        namespace: public
        group: DEFAULT_GROUP

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0

minio:
  endpoint: http:centos:9001
  accessKey: admin
  secretKey: admin123
  bucketName: coupon

rocketmq:
  name-server: 192.168.17.128:9876
  producer:
    group: iCoupon-distribution-producer-group
    send-message-timeout: 5000
    retry-times-when-send-failed: 5
    retry-times-when-send-async-failed: 5