server:
  port: 10007
spring:
  application:
    name: iCoupon-agent
  datasource:
    url: jdbc:mysql://192.168.17.128:3306/coupon?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000 # ??????????????????????
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat, wall, log4j
      use-global-lock: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
  data:
    redis:
      host: 192.168.17.128
      port: 6379
      timeout: 3000
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.17.128:8848
        namespace: 3a7a5fd9-816a-4f3d-ae91-38c4efe1c04e
        group: DEFAULT_GROUP
        cluster-name: default
        register-enabled: true
  ai:
    openai:
      api-key: sk-Vk97glBeYQjmlkb7dPhcYdNDdOZljSHYtEIytJqB536kb26u
      base-url: https://chatapi.littlewheat.com
    deepseek:
      api-key: sk-734278d90584471e98e7ee0058835104
      chat:
        options:
          model: deepseek-reasoner
    dashscope:
      api-key: sk-50f0cffc158046dcbbf7709e8a05e84f
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/schema/mysql.sql

springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zicca.icoupon

knife4j:
  enable: true
  setting:
    language:


